export const projects = {
  "instagram-local": {
    title: "Instagram Local Feed",
    description: "Instagram connects us to the world, but when it comes to our own neighborhoods, the experience falls short. Bridging global reach with local connections to help users discover events and businesses in their neighborhood.",
    role: "Product Designer",
    duration: "2-4 weeks",
    imageUrl: "/assets/instagram-local.png",
    bgColor: "#E1F5FE",
    tags: ["Product Design", "UX Strategy", "Neighborhoods"],
    externalUrl: "https://shareefpadar167.medium.com/designing-instagrams-local-feed-bridging-global-reach-with-local-connections-82e6dbbc813f",
    externalLabel: "Read full story on Medium",
    stack: "",
    secondaryUrl: "",
    secondaryLabel: "",
    problem: "Instagram's local discoverability was underwhelming, with content buried under global hashtags. Users lacked a direct, intuitive way to connect with nearby events and creators in real-time.",
    solution: "A hyper-local feed integrated into the home navigation, utilizing geolocation to surface community-driven content and small business highlights seamlessly.",
    growth: "Navigating the thin line between personalization and privacy was the biggest takeaway. Local trust is a currency managed through clear UI patterns and user-consented geolocation mapping.",
    metric: "+45%",
    metricLabel: "User growth"
  },

  "omni-cast-ai": {
    title: "OmniCast AI",
    description: "AI-powered publishing assistant that predicts performance and optimizes multi-channel campaigns in real-time.",
    role: "Senior Product Designer",
    duration: "2-4 weeks",
    imageUrl: "/assets/omnicast-preview.png",
    bgColor: "#F0F4F8",
    tags: ["AI", "SaaS", "Product Design"],
    externalUrl: "https://www.notion.so/shareef-padar/OmniCast-AI-AI-Powered-Multi-Channel-Publishing-Assistant-23a967e98ad980d88a54ffac2e1e4e93",
    externalLabel: "Read on Notion",
    stack: "",
    secondaryUrl: "",
    secondaryLabel: "",
    problem: "Agencies and creators were drowning in fragmented workflows. Marketing teams had to guess optimal posting times and switch between four different AI tools just to draft a single omnichannel campaign.",
    solution: "We replaced 'black box' automation with an in-line AI workflow. By integrating predictive scheduling and real-time engagement insights directly into the content calendar, we eliminated the friction between planning and execution.",
    growth: "Achieved a significant uplift in engagement and saved users hours of manual work. Key takeaway: Explainability is critical. Users trust AI more when it provides clear confidence scores and allows for manual overrides.",
    metric: "+20%",
    metricLabel: "Engagement Lift"
  },
  "roomy": {
    title: "Roomy: The Bedspace OS",
    description: "A high-performance, mobile-first system designed to automate the management of 21-person shared living spaces.",
    role: "Founding Engineer & Designer",
    duration: "2-4 weeks",
    imageUrl: "/assets/roomy-preview.png",
    bgColor: "#F5F3FF",
    tags: ["Full Stack", "SaaS", "Bedspace OS"],
    stack: "Next.js 16 • React 19 • Tailwind CSS 4 • Cursor (AI-IDE)",
    externalUrl: "https://roomy-delta.vercel.app/",
    externalLabel: "Launch Live App",
    secondaryUrl: "https://github.com/ShareefPadar/Roomy",
    secondaryLabel: "View Repository",
    problem: "Co-living in high-density spaces like Dubai is a logistical disaster. With 21 roommates, financial transparency is zero and shared facilities like laundry are constant points of conflict. Core challenges included financial fog from lost receipts and manual rent overhead.",
    solution: "I architected a custom Pseudo-Relational Database Engine using LocalStorage. The system features Smart Ledger Logic for real-time balance recalculation, a Live-Status Scheduler for laundry with hard daily limits, and a role-based UI for Admins and Members.",
    growth: "This project was a deep dive into Vibe Coding. By using AI to handle boilerplate and complex state synchronization, I was able to focus on the system architecture. I learned to build a database client that provides a zero-latency user experience that feels like a native app.",
    metric: "-85%",
    metricLabel: "Manual Overhead Reduction"
  },
  "almosafer-audit": {
    title: "Almosafer UX Audit",
    description: "Refining the interface of the Middle East's leading travel platform by applying core UX principles to eliminate decision fatigue.",
    role: "Product Designer",
    duration: "2-4 weeks",
    imageUrl: "/assets/almosafer-preview.png",
    bgColor: "#E3F2FD",
    tags: ["UX Research", "Hick's Law", "Travel"],
    externalUrl: "https://shareefpadar167.medium.com/applying-hicks-law-and-visual-hierarchy-to-almosafer-s-interface-e2aa36a0d932",
    externalLabel: "Read full story on Medium",
    stack: "",
    secondaryUrl: "",
    secondaryLabel: "",
    problem: "The homepage was a minefield of decision paralysis. Hick's Law was regularly violated with repetitive icons, equal-weight service buttons, and visual clutter that overwhelmed users during the critical booking moments.",
    solution: "I consolidated niche services into a streamlined 'Travel Essentials' category and redefined the visual hierarchy. By creating distinct primary and secondary signifiers, we cleared the user's path toward the most important booking actions.",
    growth: "Significant reduction in time-to-decision and improved booking velocity. The audit proved that even minor, time-boxed UX corrections can drastically improve user confidence and conversion in high-traffic travel platforms.",
    metric: "Fast",
    metricLabel: "Booking Velocity"
  },
};
