export const projects = {
  "google-maps-route-pass": {
    title: "Google Maps Route Pass",
    description: "A privacy-first, encrypted handshake for instant multi-stop navigation transfers between passengers and drivers.",
    homeDescription: "Bridging the digital handshake with an encrypted solution for universal multi-stop navigation.",
    homeImageUrl: "/assets/google-maps-preview.png",
    role: "Lead Product Designer",
    type: "Product concept",
    duration: "4 weeks",
    outcome: "Concept validated with 19 commuters — unanimous adoption intent; the QR handshake flow is designed to complete in under 5 seconds.",
    imageUrl: "/assets/google-maps-preview.png",
    bgColor: "#E1F2ED",
    tags: ["UX Research", "Privacy", "Navigation"],
    externalUrl: "https://shareef-padar.notion.site/Google-Maps-Route-Pass-UX-Case-Study-32c967e98ad98113aacfe1ab0817022e",
    externalLabel: "Read full study on Notion",
    problem: "53% of users avoid multi-stop routes because they are too difficult to explain, while 63% rely on error-prone verbal directions that often lead to privacy vulnerabilities.",
    solution: "A QR-based, encrypted handshake that allows for the instant transfer of multi-stop routes. Includes 'Destination Masking' to protect user privacy for final stops.",
    growth: "100% of surveyed users cited the passive handshake as 'faster' and 'safer.' The project successfully shifted the focus from purely functional speed to establishing emotional trust.",
    metric: "<5s",
    metricLabel: "Handshake time",
    quote: "By treating privacy as a core product feature rather than an afterthought, the solution becomes a viable tool for global commuters in diverse privacy-conscious markets."
  },

  "omni-cast-ai": {
    title: "OmniCast AI",
    description: "AI-powered publishing assistant that predicts performance and optimizes multi-channel campaigns in real-time.",
    role: "Senior Product Designer",
    type: "Product concept",
    duration: "2-4 weeks",
    outcome: "Projected +15–20% engagement uplift and 30–40% time saved in test scenarios, grounded in interviews with 8 practitioners.",
    imageUrl: "/assets/omnicast-preview.png",
    bgColor: "#F5F3FF",
    tags: ["AI", "SaaS", "Product Design"],
    externalUrl: "https://www.notion.so/shareef-padar/OmniCast-AI-AI-Powered-Multi-Channel-Publishing-Assistant-23a967e98ad980d88a54ffac2e1e4e93",
    externalLabel: "Read on Notion",
    stack: "",
    secondaryUrl: "",
    secondaryLabel: "",
    problem: "Agencies and creators were drowning in fragmented workflows. Marketing teams had to guess optimal posting times and switch between four different AI tools just to draft a single omnichannel campaign.",
    solution: "We replaced 'black box' automation with an in-line AI workflow. By integrating predictive scheduling and real-time engagement insights directly into the content calendar, we eliminated the friction between planning and execution.",
    growth: "Achieved a significant uplift in engagement and saved users hours of manual work. Key takeaway: Explainability is critical. Users trust AI more when it provides clear confidence scores and allows for manual overrides.",
    metric: "+15–20%",
    metricLabel: "Projected engagement lift",
    quote: "AI-powered publishing assistant built on 8 interviews and 4 competitor audits. Projected 30–40% time savings and 15–20% engagement uplift across 6 platforms."
  },

  "almosafer-audit": {
    title: "Almosafer UX Audit",
    description: "Refining the interface of the Middle East's leading travel platform by applying core UX principles to eliminate decision fatigue.",
    homeDescription: "Applying Hick's Law and Visual Hierarchy to streamline the Middle East's leading travel platform.",
    role: "Product Designer",
    type: "Self-initiated UX audit",
    duration: "2-4 weeks",
    outcome: "Two high-stakes booking-funnel friction points resolved entirely within the existing design system — zero brand changes.",
    imageUrl: "/assets/almosafer-preview.png",
    bgColor: "#FEFCE8",
    tags: ["UX Research", "Hick's Law", "Travel"],
    externalUrl: "https://shareefpadar167.medium.com/applying-hicks-law-and-visual-hierarchy-to-almosafer-s-interface-e2aa36a0d932",
    externalLabel: "Read full story on Medium",
    stack: "",
    secondaryUrl: "",
    secondaryLabel: "",
    problem: "The homepage was a minefield of decision paralysis. Hick's Law was regularly violated with repetitive icons, equal-weight service buttons, and visual clutter that overwhelmed users during the critical booking moments.",
    solution: "I consolidated niche services into a streamlined 'Travel Essentials' category and redefined the visual hierarchy. By creating distinct primary and secondary signifiers, we cleared the user's path toward the most important booking actions.",
    growth: "Significant reduction in time-to-decision and improved booking velocity. The audit proved that even minor, time-boxed UX corrections can drastically improve user confidence and conversion in high-traffic travel platforms.",
    metric: "2",
    metricLabel: "High-stakes fixes",
    quote: "Audited the Middle East's leading travel platform. Identified two high-stakes friction points in the booking funnel — resolved with zero brand changes."
  },

  "instagram-local": {
    title: "Instagram Local Feed",
    description: "Instagram connects us to the world, but when it comes to our own neighborhoods, the experience falls short. Bridging global reach with local connections to help users discover events and businesses in their neighborhood.",
    homeDescription: "Bridging global reach with local connections to help users discover events and businesses in their neighborhood.",
    role: "Product Designer",
    type: "Product concept",
    duration: "2-4 weeks",
    outcome: "Two discovery patterns — passive and active intent — designed from a 20-user survey that found 86% value local content but fewer than half can find it.",
    imageUrl: "/assets/instagram-local.png",
    homeImageUrl: "https://miro.medium.com/v2/resize:fit:780/1*3sIpxdG2WHXa9JyB9dI_lA.png",
    bgColor: "#EDF9FF",
    tags: ["Product Design", "UX Strategy", "Neighborhoods"],
    externalUrl: "https://shareefpadar167.medium.com/designing-instagrams-local-feed-bridging-global-reach-with-local-connections-82e6dbbc813f",
    externalLabel: "Read full story on Medium",
    stack: "",
    secondaryUrl: "",
    secondaryLabel: "",
    problem: "Instagram's local discoverability was underwhelming, with content buried under global hashtags. Users lacked a direct, intuitive way to connect with nearby events and creators in real-time.",
    solution: "A hyper-local feed integrated into the home navigation, utilizing geolocation to surface community-driven content and small business highlights seamlessly.",
    growth: "Navigating the thin line between personalization and privacy was the biggest takeaway. Local trust is a currency managed through clear UI patterns and user-consented geolocation mapping.",
    metric: "20",
    metricLabel: "Users surveyed",
    quote: "Uncovered a critical gap: 86% of users value local content, but fewer than half can find it. Surveyed 20 users, designed 2 discovery solutions for passive and active browsing modes."
  },

  "form": {
    title: "Form: Privacy-First Health",
    description: "A health tracker built on one product insight: removing account friction beats adding features. Works fully offline with no sign-up — weight, BMI, and body composition stay on your device, syncing only when you choose.",
    homeDescription: "A privacy-first, offline-ready health tracker with smart goal forecasting and on-device macro targets.",
    role: "Product Designer & Builder",
    type: "Live product",
    outcome: "Live and offline-first — full tracking with zero sign-up; data stays on-device and syncs only when the user opts in.",
    duration: "2-4 weeks",
    imageUrl: "/assets/fitness-tracker-preview.png",
    bgColor: "#0D1117",
    tags: ["Full Stack", "Offline-First", "Health Tech"],
    stack: "React + Vite • IndexedDB (Dexie.js) • Supabase • Recharts",
    externalUrl: "https://fitness-tracker-pi-tan.vercel.app/",
    externalLabel: "Launch Live App",
    secondaryUrl: "https://github.com/ShareefPadar/fitness-tracker",
    secondaryLabel: "View Repository",
    problem: "Most fitness apps are cloud-dependent, privacy-invasive, and locked behind subscriptions. Users with intermittent connectivity or privacy concerns had no premium alternative that worked offline-first without sacrificing UX quality.",
    solution: "Built a local-first architecture using IndexedDB (Dexie.js) as the primary data layer, with optional Supabase sync for multi-device users. Guest Mode enables full-featured tracking without an account — privacy as a core product feature, not a settings toggle. Macro targets are calculated on-device using the Mifflin-St Jeor BMR formula.",
    growth: "Building local-first taught me to design around data ownership: schema, sync conflict resolution, and export formats are user-controlled by default. The dual Guest/Sync mode pattern proved that reducing account friction is a stronger retention hook than feature richness.",
    metric: "0ms",
    metricLabel: "Load Time (Offline)",
    quote: "Privacy-first doesn't mean feature-poor. Guest Mode plus offline-first architecture delivers a premium UX with zero account friction."
  },

  "roomy": {
    title: "Roomy: The Bedspace OS",
    description: "Living with 21 roommates broke every spreadsheet — so I designed and shipped a role-based system of record for rent, utilities, and shared facilities, now in daily use.",
    role: "Product Designer & Builder",
    type: "Live product",
    duration: "2-4 weeks",
    outcome: "Running in production for a 21-person flat — rent, utilities, and laundry on one shared system of record.",
    imageUrl: "/assets/roomy-preview.png",
    bgColor: "#F5F3FF",
    tags: ["Full Stack", "SaaS", "Bedspace OS"],
    stack: "Next.js 16 • React 19 • Tailwind CSS 4 • Cursor (AI-IDE)",
    externalUrl: "https://roomy-delta.vercel.app/",
    externalLabel: "Launch Live App",
    secondaryUrl: "https://github.com/ShareefPadar/Roomy",
    secondaryLabel: "View Repository",
    problem: "Co-living in high-density spaces like Dubai is a logistical disaster. With 21 roommates, financial transparency is zero and shared facilities like laundry are constant points of conflict. Core challenges included financial fog from lost receipts and manual rent overhead.",
    solution: "I architected a custom Pseudo-Relational Database Engine using LocalStorage. The system features Smart Ledger Logic for real-time balance recalculation, a Live-Status Scheduler for laundry with hard daily limits, and a role-based UI for Admins and Members.",
    growth: "This project was a deep dive into Vibe Coding. By using AI to handle boilerplate and complex state synchronization, I was able to focus on the system architecture. I learned to build a database client that provides a zero-latency user experience that feels like a native app.",
    metric: "-85%",
    metricLabel: "Manual Overhead Reduction",
    quote: ""
  },
};
